# Generated by Django 2.0.5 on 2018-07-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=20)),
                ('end_data', models.DateField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'module',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tea_id', models.IntegerField()),
                ('path', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('role', models.BooleanField(default=False)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('tea_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_relation',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimilarityApp.Project'),
        ),
    ]
