# Generated by Django 2.0.5 on 2018-07-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimilarityApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
